brewing:
  xp-enabled: true
  xp-amounts:
    turtle_helmet: 2.0
    rabbit_foot: 2.0
    breeze_rod: 1.0
    phantom_membrane: 1.0
    ghast_tear: 1.0
    slime_block: 1.0
    cobweb: 1.0
    dragon_breath: 1.0
    golden_carrot: 0.7
    blaze_powder: 0.7
    glistering_melon_slice: 0.7
    pufferfish: 0.7
    gunpowder: 0.7
    fermented_spider_eye: 0.7
    magma_cream: 0.7
    redstone: 0.5
    glowstone_dust: 0.5
    sugar: 0.5
    spider_eye: 0.5
    stone: 0.5
farming:
  xp-enabled: true
  require-tool: true
  valid-tools:
    - WOODEN_HOE
    - STONE_HOE
    - IRON_HOE
    - GOLDEN_HOE
    - DIAMOND_HOE
    - NETHERITE_HOE
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE
  xp-amounts:
    wheat: 0.1
    beetroot: 0.1
    pumpkin: 0.1
    melon: 0.1
    torchflower: 0.5
    pitcher_plant: 0.5
    cocoa: 0.1
    sweet_berries: 0.05
    glow_berries: 0.05
shearing:
  xp-enabled: true
  xp-amounts:
    sheep: 0.2
    mooshroom: 0.5
    bogged: 0.7
    snow_golem: 0.0
archeology:
  xp-enabled: true
  xp-amounts:
    suspicious_sand: 0.8
    suspicious_gravel: 0.8
fortune-boost:
  enabled: true
  level-multipliers:
    1: 1.5
    2: 2.0
    3: 2.5
misc:
  xp-enabled: false
  xp-amounts:
    piglin-barter: 0.1
